### ISSUE TITLE
with kernel 5.13 doesn't work

### ISSUE THREAD

**Issue by yuiiio** [Plippo/asus-wmi-screenpad#24]
I have test with kernel 5.13.0 and asus-wmi-screenpad latest master.
but not shown /sys/class/leds/asus::screenpad directory.
kernel 5.12 is works.

**Comment by yuiiio** [comment]
sorry
maybe my kernel config issue.
module compressed by zstd in config, so change to xz and works.
I'm not sure it is kernel, dkms, gcc or distro-config bugs.

**Comment by SacDin** [comment]
how did you managed to resolve this ?
