### ISSUE TITLE
Create a package for automatic installation

### ISSUE THREAD

**Issue by bphd** [Plippo/asus-wmi-screenpad#4]
You can copy the package `acpi_call-dkms` because it makes nearly the same thing

**Comment by Plippo** [comment]
This repository is only a temporary solution, once it is stable I will try to get it to the kernel so we won't have to build it manually any more. Also maintaining packages would be a hassle as they have to be adapted for every kernel version. So I won't create a package as this is only about getting it to work until it is included in the kernel. But of course, if someone wants to create packages, feel free to do so.
